"""initial schema

Revision ID: 650e92a007d2
Revises: 
Create Date: 2026-07-18 23:21:57.181199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '650e92a007d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_contracts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=False),
    sa.Column('allowed_metrics', sa.JSON(), nullable=False),
    sa.Column('allowed_dimensions', sa.JSON(), nullable=False),
    sa.Column('time_granularity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_contracts_dataset_version_id'), 'analysis_contracts', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_analysis_contracts_id'), 'analysis_contracts', ['id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_contract_id', sa.Uuid(), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_analysis_contract_id'), 'analysis_results', ['analysis_contract_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_dataset_version_id'), 'analysis_results', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    op.create_table('chart_customizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=False),
    sa.Column('chart_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('customizations_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_customizations_chart_id'), 'chart_customizations', ['chart_id'], unique=False)
    op.create_index(op.f('ix_chart_customizations_dataset_version_id'), 'chart_customizations', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_chart_customizations_id'), 'chart_customizations', ['id'], unique=False)
    op.create_index(op.f('ix_chart_customizations_user_id'), 'chart_customizations', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_dataset_id'), 'chat_sessions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('cleaning_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=False),
    sa.Column('proposed_actions', sa.JSON(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cleaning_plans_dataset_version_id'), 'cleaning_plans', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_cleaning_plans_id'), 'cleaning_plans', ['id'], unique=False)
    op.create_table('dataset_tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('source_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('schema_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_tables_id'), 'dataset_tables', ['id'], unique=False)
    op.create_index(op.f('ix_dataset_tables_version_id'), 'dataset_tables', ['version_id'], unique=False)
    op.create_table('inspection_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=False),
    sa.Column('issues_detected', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_reports_dataset_version_id'), 'inspection_reports', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_inspection_reports_id'), 'inspection_reports', ['id'], unique=False)
    op.create_table('mapping_corrections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('column_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('proposed_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('corrected_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('column_dtype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('corrected_by', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_corrections_dataset_id'), 'mapping_corrections', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_mapping_corrections_id'), 'mapping_corrections', ['id'], unique=False)
    op.create_table('saved_dashboards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_dashboards_dataset_id'), 'saved_dashboards', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_saved_dashboards_id'), 'saved_dashboards', ['id'], unique=False)
    op.create_index(op.f('ix_saved_dashboards_user_id'), 'saved_dashboards', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('llm_settings', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('intent_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_index(op.f('ix_datasets_owner_id'), 'datasets', ['owner_id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('UPLOAD', 'SQL', 'CLEAN', name='sourcetype'), nullable=False),
    sa.Column('source_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cleaned_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('schema_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schema_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('change_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('chart_configs_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semantic_map_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('duckdb_table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active_join_view', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('join_config_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_versions_dataset_id'), 'dataset_versions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_id'), 'dataset_versions', ['id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_parent_version_id'), 'dataset_versions', ['parent_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_versions_parent_version_id'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_id'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_dataset_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_datasets_owner_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_saved_dashboards_user_id'), table_name='saved_dashboards')
    op.drop_index(op.f('ix_saved_dashboards_id'), table_name='saved_dashboards')
    op.drop_index(op.f('ix_saved_dashboards_dataset_id'), table_name='saved_dashboards')
    op.drop_table('saved_dashboards')
    op.drop_index(op.f('ix_mapping_corrections_id'), table_name='mapping_corrections')
    op.drop_index(op.f('ix_mapping_corrections_dataset_id'), table_name='mapping_corrections')
    op.drop_table('mapping_corrections')
    op.drop_index(op.f('ix_inspection_reports_id'), table_name='inspection_reports')
    op.drop_index(op.f('ix_inspection_reports_dataset_version_id'), table_name='inspection_reports')
    op.drop_table('inspection_reports')
    op.drop_index(op.f('ix_dataset_tables_version_id'), table_name='dataset_tables')
    op.drop_index(op.f('ix_dataset_tables_id'), table_name='dataset_tables')
    op.drop_table('dataset_tables')
    op.drop_index(op.f('ix_cleaning_plans_id'), table_name='cleaning_plans')
    op.drop_index(op.f('ix_cleaning_plans_dataset_version_id'), table_name='cleaning_plans')
    op.drop_table('cleaning_plans')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_dataset_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_chart_customizations_user_id'), table_name='chart_customizations')
    op.drop_index(op.f('ix_chart_customizations_id'), table_name='chart_customizations')
    op.drop_index(op.f('ix_chart_customizations_dataset_version_id'), table_name='chart_customizations')
    op.drop_index(op.f('ix_chart_customizations_chart_id'), table_name='chart_customizations')
    op.drop_table('chart_customizations')
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_dataset_version_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_analysis_contract_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_analysis_contracts_id'), table_name='analysis_contracts')
    op.drop_index(op.f('ix_analysis_contracts_dataset_version_id'), table_name='analysis_contracts')
    op.drop_table('analysis_contracts')
    # ### end Alembic commands ###
